---
abstract: 'Find the locations in your PATH where commands appear'
author:
  - 'Chris Williams'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Executable
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  Path::Executable:
    file: lib/Path/Executable.pm
    version: 0.02
requires:
  File::Spec: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/path-executable/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/path-executable.git
version: 0.02
